### ISSUE TITLE
Zkill Watcher pulling old kills

### ISSUE THREAD

**Issue by rufjame** [ghoti/DiscordRooster#4]
Can a 48 hour or 7 day or 1 year KM limit be put on the watcher so it doesn't post stuff from days past.

**Comment by ghoti** [comment]
apparently fixed and was a zkill issue.

**Comment by MordecaiMalignatus** [comment]
I have an actual fix for this as well, this happens whenever chars are added to zkill that zkill does not yet have, and then gains access to. RedisQ pulls from all new killmails in zkill, even those old that only now got added. I'll throw in a oneliner in a bit. 

e: Wait I'm fucking dumb, the fix is already in because I pushed it to the wrong branch and I also cant read >_>

**Comment by MordecaiMalignatus** [comment]
Actually hold the fucking phone, this isn't even in this repo yet. This thing is referencing _my fork_ of it where I fixed it, but it's not yet in here. Github pls.
